#!/usr/bin/env bash
#
# setup-local.sh — install gnatcode as a globally-available command on this machine.
#
# This sets up a "live iteration" launcher: a small script on your PATH that runs
# the TypeScript source directly through Bun, so source edits take effect
# immediately with no rebuild step.
#
# Usage:
#   ./script/setup-local.sh            # install using defaults
#   ./script/setup-local.sh --uninstall
#
# Environment overrides:
#   GNATCODE_BIN_DIR   directory to install the launcher into (default: $HOME/bin)
#   GNATCODE_BUN       path to the bun binary (default: autodetected)
#
set -euo pipefail

# ---------------------------------------------------------------------------
# Resolve repo location from this script's path, so it works from anywhere.
# ---------------------------------------------------------------------------
SCRIPT_PATH="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_DIR="$(cd "$SCRIPT_PATH/.." && pwd)"
PKG_DIR="$REPO_DIR/packages/opencode"

BIN_DIR="${GNATCODE_BIN_DIR:-$HOME/bin}"
LAUNCHER="$BIN_DIR/gnatcode"
RC_FILE="${GNATCODE_RC_FILE:-$HOME/.zshrc}"
PATH_LINE="export PATH=\"$BIN_DIR:\$PATH\""

info()  { printf '\033[1;34m==>\033[0m %s\n' "$*"; }
warn()  { printf '\033[1;33m warn:\033[0m %s\n' "$*" >&2; }
fail()  { printf '\033[1;31merror:\033[0m %s\n' "$*" >&2; exit 1; }

# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------
if [[ "${1:-}" == "--uninstall" ]]; then
  info "Removing launcher $LAUNCHER"
  rm -f "$LAUNCHER"
  if [[ -f "$RC_FILE" ]] && grep -qF "$PATH_LINE" "$RC_FILE"; then
    info "Removing PATH line from $RC_FILE"
    # Portable in-place delete (BSD + GNU sed differ; use a temp file).
    # Also drop the marker comment we add above the line.
    grep -vF "$PATH_LINE" "$RC_FILE" | grep -vxF "# gnatcode local CLI" > "$RC_FILE.tmp" \
      && mv "$RC_FILE.tmp" "$RC_FILE"
  fi
  info "Done. Open a new terminal for the PATH change to take effect."
  exit 0
fi

# ---------------------------------------------------------------------------
# Preconditions
# ---------------------------------------------------------------------------
[[ -d "$PKG_DIR" ]] || fail "could not find $PKG_DIR — is this a gnatcode checkout?"

info "Repository:  $REPO_DIR"
info "Packages:    $PKG_DIR"

# Locate bun.
BUN_BIN="${GNATCODE_BUN:-$(command -v bun || true)}"
if [[ -z "$BUN_BIN" ]]; then
  # Fall back to the common npm-global location used during initial setup.
  for candidate in "$HOME/.node_modules/bin/bun" /opt/homebrew/bin/bun /usr/local/bin/bun; do
    [[ -x "$candidate" ]] && BUN_BIN="$candidate" && break
  done
fi
[[ -n "$BUN_BIN" && -x "$BUN_BIN" ]] || fail "bun not found. Install it first: npm install -g bun"
info "Using bun:   $BUN_BIN ($("$BUN_BIN" --version))"

[[ -f "$PKG_DIR/bunfig.toml" ]] || fail "missing $PKG_DIR/bunfig.toml (Solid JSX preload config)"

# ---------------------------------------------------------------------------
# Install dependencies
# ---------------------------------------------------------------------------
if [[ ! -d "$REPO_DIR/node_modules" ]]; then
  info "Installing dependencies (bun install --ignore-scripts)"
  # --ignore-scripts avoids native build failures (e.g. tree-sitter-powershell)
  # that are irrelevant to running the TUI/CLI from source.
  ( cd "$REPO_DIR" && "$BUN_BIN" install --ignore-scripts ) || warn "bun install reported errors; continuing"
else
  info "node_modules present, skipping dependency install"
  info "  (run 'bun install --ignore-scripts' manually if deps look stale)"
fi

# node-pty needs its spawn-helper to be executable, otherwise the TUI can't
# start a shell. This is what the repo's postinstall normally does.
info "Fixing node-pty permissions"
( cd "$PKG_DIR" && "$BUN_BIN" run --cwd packages/core fix-node-pty ) 2>/dev/null \
  || ( cd "$REPO_DIR/packages/core" && "$BUN_BIN" run fix-node-pty ) \
  || warn "could not run fix-node-pty; TUI terminal may fail if spawn-helper is not executable"

# ---------------------------------------------------------------------------
# Write the launcher
# ---------------------------------------------------------------------------
info "Installing launcher to $LAUNCHER"
mkdir -p "$BIN_DIR"
cat > "$LAUNCHER" <<EOF
#!/usr/bin/env bash
# Live-iteration launcher for gnatcode TUI/CLI.
# Runs the TypeScript source directly via Bun, so edits take effect immediately.
# Generated by $REPO_DIR/script/setup-local.sh
set -e
cd "$PKG_DIR"
exec "$BUN_BIN" run ./src/index.ts "\$@"
EOF
chmod +x "$LAUNCHER"

# ---------------------------------------------------------------------------
# Ensure BIN_DIR is on PATH
# ---------------------------------------------------------------------------
case ":$PATH:" in
  *":$BIN_DIR:"*) info "$BIN_DIR already on PATH" ;;
  *)
    if [[ -f "$RC_FILE" ]] && grep -qF "$PATH_LINE" "$RC_FILE"; then
      info "$BIN_DIR already configured in $RC_FILE"
    else
      info "Adding $BIN_DIR to PATH in $RC_FILE"
      {
        printf '\n# gnatcode local CLI\n'
        printf '%s\n' "$PATH_LINE"
      } >> "$RC_FILE"
    fi
    ;;
esac

# ---------------------------------------------------------------------------
# Smoke test
# ---------------------------------------------------------------------------
info "Smoke test"
if "$LAUNCHER" --version >/dev/null 2>&1; then
  info "gnatcode runs OK ($("$LAUNCHER" --version 2>/dev/null | tail -1))"
else
  warn "launcher did not run cleanly; try '$LAUNCHER --help' to see the error"
fi

cat <<EOF

$(info "Setup complete")

  Command:  gnatcode
  Launcher: $LAUNCHER
  Source:   $PKG_DIR/src/index.ts

Open a NEW terminal (so PATH is refreshed), then run:

  gnatcode            # launch the TUI
  gnatcode --help

Edits to the source take effect immediately — just re-run gnatcode.

To remove this setup later:

  $REPO_DIR/script/setup-local.sh --uninstall
EOF
